name: movies
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  dio: ^5.1.2
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  retrofit: ^4.0.1
  dartz: ^0.10.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.2
  freezed: ^2.3.3
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  retrofit_generator: ^6.0.0+3


flutter:

  uses-material-design: true

